-- MySQL Script generated by MySQL Workbench
-- Sun Dec 20 05:56:45 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MidPJ
-- -----------------------------------------------------
-- For PJ

-- -----------------------------------------------------
-- Schema MidPJ
--
-- For PJ
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MidPJ` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `MidPJ` ;

-- -----------------------------------------------------
-- Table `MidPJ`.`Accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MidPJ`.`Accounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `RealName` VARCHAR(100) NOT NULL,
  `UserName` VARCHAR(45) NOT NULL,
  `UserEmail` VARCHAR(30) NOT NULL,
  `UserPassword` VARCHAR(45) NOT NULL,
  `Bio` VARCHAR(150) NULL,
  PRIMARY KEY (`id`, `RealName`, `UserEmail`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MidPJ`.`advertisement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MidPJ`.`advertisement` (
  `idAdvertisement` INT NOT NULL AUTO_INCREMENT,
  `AdvertisementFile` VARCHAR(300) NOT NULL,
  `AdvertisementShowDate` VARCHAR(45) NOT NULL,
  `PayDate` VARCHAR(45) NOT NULL,
  `Paytime` VARCHAR(45) NOT NULL,
  `Paytotal` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdvertisement`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `MidPJ`.`music`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MidPJ`.`music` (
  `idMusic` INT NOT NULL AUTO_INCREMENT,
  `MusicName` VARCHAR(45) NOT NULL,
  `MusicArtist` VARCHAR(45) NOT NULL,
  `MusicPath` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMusic`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
